name: Check & fix styling

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.0'
            coverage: none

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run PHP CS Fixer
        run: composer format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
